#!/bin/sh

git add --all
git commit -m "Clean things up at $(date --rfc-3339=seconds)"
git tag "cleanup-$(date --rfc-3339=date)"

echo
echo "Use 'git push origin --tags' to push all tags to remote."
echo
