/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef DIRECTORYCONTENTTABLE_OIDS_H
#define DIRECTORYCONTENTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table DirectoryContentTable */
#define DIRECTORYCONTENTTABLE_OID 1, 3, 6, 1, 4, 1, 8072, 7777, 1, 4


#define COLUMN_DIRECTORYENTRYINDEX 1

#define COLUMN_DIRECTORYENTRYPATH 2

#define COLUMN_DIRECTORYENTRYMASK 3


#define DIRECTORYCONTENTTABLE_MIN_COL COLUMN_DIRECTORYENTRYINDEX
#define DIRECTORYCONTENTTABLE_MAX_COL COLUMN_DIRECTORYENTRYMASK


#ifdef __cplusplus
}
#endif

#endif /* DIRECTORYCONTENTTABLE_OIDS_H */
