/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "DirectoryContentTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement DirectoryContentTable get routines.
 * TODO:240:M: Implement DirectoryContentTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table DirectoryContentTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MONITOR-MIB::DirectoryContentTable is subid 4 of netSnmpModuleIDs.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.8072.3.1.4, length: 10
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement DirectoryContentTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param DirectoryEntryIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int DirectoryContentTable_indexes_set_tbl_idx(
    DirectoryContentTable_mib_index* tbl_idx, long DirectoryEntryIndex_val) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_indexes_set_tbl_"
         "idx",
         "called\n"));

    /* DirectoryEntryIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    tbl_idx->DirectoryEntryIndex = DirectoryEntryIndex_val;


    return MFD_SUCCESS;
} /* DirectoryContentTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int DirectoryContentTable_indexes_set(
    DirectoryContentTable_rowreq_ctx* rowreq_ctx,
    long DirectoryEntryIndex_val) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_indexes_set",
         "called\n"));

    if (MFD_SUCCESS
        != DirectoryContentTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx,
                                                     DirectoryEntryIndex_val))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if (0 != DirectoryContentTable_index_to_oid(&rowreq_ctx->oid_idx,
                                                &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* DirectoryContentTable_indexes_set */


/*---------------------------------------------------------------------
 * MONITOR-MIB::DirectoryContentEntry.DirectoryEntryPath
 * DirectoryEntryPath is subid 2 of DirectoryContentEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.8072.3.1.4.1.2
 * Description:
Directory entry path.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the DirectoryEntryPath data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param DirectoryEntryPath_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param DirectoryEntryPath_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by DirectoryEntryPath.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*DirectoryEntryPath_val_ptr_len_ptr) bytes of
*memory,
 *       allocate it using malloc() and update DirectoryEntryPath_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int DirectoryEntryPath_get(DirectoryContentTable_rowreq_ctx* rowreq_ctx,
                           char** DirectoryEntryPath_val_ptr_ptr,
                           size_t* DirectoryEntryPath_val_ptr_len_ptr) {
    /** we should have a non-NULL pointer and enough storage */
    netsnmp_assert((NULL != DirectoryEntryPath_val_ptr_ptr)
                   && (NULL != *DirectoryEntryPath_val_ptr_ptr));
    netsnmp_assert(NULL != DirectoryEntryPath_val_ptr_len_ptr);


    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryEntryPath_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the DirectoryEntryPath data.
     * copy (* DirectoryEntryPath_val_ptr_ptr ) data and (*
     * DirectoryEntryPath_val_ptr_len_ptr ) from rowreq_ctx->data
     */
    /*
     * make sure there is enough space for DirectoryEntryPath data
     */
    if ((NULL == (*DirectoryEntryPath_val_ptr_ptr))
        || ((*DirectoryEntryPath_val_ptr_len_ptr)
            < (rowreq_ctx->data.DirectoryEntryPath_len
               * sizeof(rowreq_ctx->data.DirectoryEntryPath[0])))) {
        /*
         * allocate space for DirectoryEntryPath data
         */
        (*DirectoryEntryPath_val_ptr_ptr) =
            malloc(rowreq_ctx->data.DirectoryEntryPath_len
                   * sizeof(rowreq_ctx->data.DirectoryEntryPath[0]));
        if (NULL == (*DirectoryEntryPath_val_ptr_ptr)) {
            snmp_log(LOG_ERR,
                     "could not allocate memory "
                     "(rowreq_ctx->data.DirectoryEntryPath)\n");
            return MFD_ERROR;
        }
    }
    (*DirectoryEntryPath_val_ptr_len_ptr) =
        rowreq_ctx->data.DirectoryEntryPath_len
        * sizeof(rowreq_ctx->data.DirectoryEntryPath[0]);
    memcpy((*DirectoryEntryPath_val_ptr_ptr),
           rowreq_ctx->data.DirectoryEntryPath,
           rowreq_ctx->data.DirectoryEntryPath_len
               * sizeof(rowreq_ctx->data.DirectoryEntryPath[0]));

    return MFD_SUCCESS;
} /* DirectoryEntryPath_get */

/*---------------------------------------------------------------------
 * MONITOR-MIB::DirectoryContentEntry.DirectoryEntryMask
 * DirectoryEntryMask is subid 3 of DirectoryContentEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.8072.3.1.4.1.3
 * Description:
Directory entry mask.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the DirectoryEntryMask data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param DirectoryEntryMask_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int DirectoryEntryMask_get(DirectoryContentTable_rowreq_ctx* rowreq_ctx,
                           long* DirectoryEntryMask_val_ptr) {
    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != DirectoryEntryMask_val_ptr);


    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryEntryMask_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the DirectoryEntryMask data.
     * copy (* DirectoryEntryMask_val_ptr ) from rowreq_ctx->data
     */
    (*DirectoryEntryMask_val_ptr) = rowreq_ctx->data.DirectoryEntryMask;

    return MFD_SUCCESS;
} /* DirectoryEntryMask_get */


/** @} */
