/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** \page MFD helper for DirectoryContentTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "DirectoryContentTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "DirectoryContentTable_interface.h"

const oid DirectoryContentTable_oid[] = {DIRECTORYCONTENTTABLE_OID};
const int DirectoryContentTable_oid_size =
    OID_LENGTH(DirectoryContentTable_oid);

DirectoryContentTable_registration DirectoryContentTable_user_context;

void initialize_table_DirectoryContentTable(void);
void shutdown_table_DirectoryContentTable(void);


/**
 * Initializes the DirectoryContentTable module
 */
void init_DirectoryContentTable(void) {
    DEBUGMSGTL(("verbose:DirectoryContentTable:init_DirectoryContentTable",
                "called\n"));

    /*
     * TODO:300:o: Perform DirectoryContentTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("DirectoryContentTable"))
        initialize_table_DirectoryContentTable();

} /* init_DirectoryContentTable */

/**
 * Shut-down the DirectoryContentTable module (agent is exiting)
 */
void shutdown_DirectoryContentTable(void) {
    if (should_init("DirectoryContentTable"))
        shutdown_table_DirectoryContentTable();
}

/**
 * Initialize the table DirectoryContentTable
 *    (Define its contents and how it's structured)
 */
void initialize_table_DirectoryContentTable(void) {
    DirectoryContentTable_registration* user_context;
    u_long flags;

    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:initialize_table_DirectoryContentTable",
         "called\n"));

    /*
     * TODO:301:o: Perform DirectoryContentTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize DirectoryContentTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context =
        netsnmp_create_data_list("DirectoryContentTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _DirectoryContentTable_initialize_interface(user_context, flags);
} /* initialize_table_DirectoryContentTable */

/**
 * Shutdown the table DirectoryContentTable
 */
void shutdown_table_DirectoryContentTable(void) {
    /*
     * call interface shutdown code
     */
    _DirectoryContentTable_shutdown_interface(
        &DirectoryContentTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to
 *rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int DirectoryContentTable_rowreq_ctx_init(
    DirectoryContentTable_rowreq_ctx* rowreq_ctx, void* user_init_ctx) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_rowreq_ctx_init",
         "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:210:o: |-> Perform extra DirectoryContentTable rowreq
     * initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* DirectoryContentTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void DirectoryContentTable_rowreq_ctx_cleanup(
    DirectoryContentTable_rowreq_ctx* rowreq_ctx) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_rowreq_ctx_"
         "cleanup",
         "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:211:o: |-> Perform extra DirectoryContentTable rowreq cleanup.
     */
} /* DirectoryContentTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int DirectoryContentTable_pre_request(
    DirectoryContentTable_registration* user_context) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_pre_request",
         "called\n"));

    /*
     * TODO:510:o: Perform DirectoryContentTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* DirectoryContentTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int DirectoryContentTable_post_request(
    DirectoryContentTable_registration* user_context, int rc) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_post_request",
         "called\n"));

    /*
     * TODO:511:o: Perform DirectoryContentTable post-request actions.
     */

    return MFD_SUCCESS;
} /* DirectoryContentTable_post_request */


/** @{ */
