/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 *
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DIRECTORYCONTENTTABLE_INTERFACE_H
#define DIRECTORYCONTENTTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "DirectoryContentTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _DirectoryContentTable_initialize_interface(
    DirectoryContentTable_registration* user_ctx, u_long flags);
void _DirectoryContentTable_shutdown_interface(
    DirectoryContentTable_registration* user_ctx);

DirectoryContentTable_registration* DirectoryContentTable_registration_get(
    void);

DirectoryContentTable_registration* DirectoryContentTable_registration_set(
    DirectoryContentTable_registration* newreg);

netsnmp_container* DirectoryContentTable_container_get(void);
int DirectoryContentTable_container_size(void);

DirectoryContentTable_rowreq_ctx* DirectoryContentTable_allocate_rowreq_ctx(
    void*);
void DirectoryContentTable_release_rowreq_ctx(
    DirectoryContentTable_rowreq_ctx* rowreq_ctx);

int DirectoryContentTable_index_to_oid(
    netsnmp_index* oid_idx, DirectoryContentTable_mib_index* mib_idx);
int DirectoryContentTable_index_from_oid(
    netsnmp_index* oid_idx, DirectoryContentTable_mib_index* mib_idx);

/*
 * access to certain internals. use with caution!
 */
void DirectoryContentTable_valid_columns_set(netsnmp_column_info* vc);


#ifdef __cplusplus
}
#endif

#endif /* DIRECTORYCONTENTTABLE_INTERFACE_H */
/** @} */
