/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#include <assert.h>

#include <errno.h>
#include <linux/limits.h>
#include <sys/stat.h>

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "DirectoryContentTable.h"


#include "DirectoryContentTable_data_access.h"

#include "GlobalSettings.h"
#include "Utility.h"


/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table DirectoryContentTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MONITOR-MIB::DirectoryContentTable is subid 4 of netSnmpModuleIDs.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.8072.3.1.4, length: 10
*/

/**
 * initialization for DirectoryContentTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param DirectoryContentTable_reg
 *        Pointer to DirectoryContentTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int DirectoryContentTable_init_data(
    DirectoryContentTable_registration* DirectoryContentTable_reg) {
    DEBUGMSGTL(("verbose:DirectoryContentTable:DirectoryContentTable_init_data",
                "called\n"));

    /*
     * TODO:303:o: Initialize DirectoryContentTable data.
     */
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    return MFD_SUCCESS;
} /* DirectoryContentTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void DirectoryContentTable_container_init(netsnmp_container** container_ptr_ptr,
                                          netsnmp_cache* cache) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_container_init",
         "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to "
                 "DirectoryContentTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,
                 "bad cache param to DirectoryContentTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up DirectoryContentTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = DIRECTORYCONTENTTABLE_CACHE_TIMEOUT; /* seconds */
} /* DirectoryContentTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before DirectoryContentTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void DirectoryContentTable_container_shutdown(
    netsnmp_container* container_ptr) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_container_"
         "shutdown",
         "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,
                 "bad params to DirectoryContentTable_container_shutdown\n");
        return;
    }

} /* DirectoryContentTable_container_shutdown */


/*
 * load directory information into container
 */
static void directory_info_loader(struct dirent* entry, int entry_index,
                                  void* data) {
    assert(entry && "entry must not be NULL");
    assert(data && "data must not be NULL");

    netsnmp_container* container = (netsnmp_container*)data;
    DirectoryContentTable_rowreq_ctx* rowreq_ctx = NULL;

    int DirectoryEntryIndex = entry_index;
    /*
        * TODO:352:M: |   |-> set indexes in new DirectoryContentTable rowreq
        * context.
        * data context will be set from the param (unless NULL,
        *      in which case a new data context will be allocated)
        */
    rowreq_ctx = DirectoryContentTable_allocate_rowreq_ctx(NULL);
    if (NULL == rowreq_ctx) {
        snmp_log(LOG_ERR, "memory allocation failed\n");
        return;
    }
    if (MFD_SUCCESS
        != DirectoryContentTable_indexes_set(rowreq_ctx, DirectoryEntryIndex)) {
        snmp_log(LOG_ERR,
                 "error setting index while loading "
                 "DirectoryContentTable data.\n");
        DirectoryContentTable_release_rowreq_ctx(rowreq_ctx);
        return;
    }

    /*
        * TODO:352:r: |   |-> populate DirectoryContentTable data context.
        * Populate data context here. (optionally, delay until row prep)
        */
    /*
        * TRANSIENT or semi-TRANSIENT data:
        * copy data or save any info needed to do it in row_prep.
        */
    /*
        * setup/save data for DirectoryEntryPath
        * DirectoryEntryPath(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
        */
    /** no mapping */
    /*
        * make sure there is enough space for DirectoryEntryPath data
        */
    char DirectoryEntryPath[NAME_MAX + 1] = {0};
    strcpy(DirectoryEntryPath, entry->d_name);

    char DirectoryEntryFullPath[PATH_MAX + 1] = {0};
    strcpy(DirectoryEntryFullPath, get_global_settings()->path);
    strcat(DirectoryEntryFullPath, entry->d_name);

    int DirectoryEntryPath_len = strnlen(DirectoryEntryPath, PATH_MAX);

    int DirectoryEntryMask = 0;
    struct stat statbuf;
    if (stat(DirectoryEntryFullPath, &statbuf) == 0) {
        int mask = statbuf.st_mode & (S_IRWXU   /* owner permissioins */
                                      | S_IRWXG /* group permissions */
                                      | S_IRWXO /* others permissions */);
        DirectoryEntryMask = ((mask >> 6) & 7) * 100 + ((mask >> 3) & 7) * 10
                             + ((mask >> 0) & 7);
    }


    rowreq_ctx->data.DirectoryEntryPath_len = DirectoryEntryPath_len;

    if ((NULL == rowreq_ctx->data.DirectoryEntryPath)
        || (rowreq_ctx->data.DirectoryEntryPath_len
            < (DirectoryEntryPath_len * sizeof(DirectoryEntryPath[0])))) {
        snmp_log(LOG_ERR, "not enough space for value (DirectoryEntryPath)\n");
        return;
    }
    rowreq_ctx->data.DirectoryEntryPath_len =
        DirectoryEntryPath_len * sizeof(DirectoryEntryPath[0]);
    memcpy(rowreq_ctx->data.DirectoryEntryPath, DirectoryEntryPath,
           DirectoryEntryPath_len * sizeof(DirectoryEntryPath[0]));

    /*
        * setup/save data for DirectoryEntryMask
        * DirectoryEntryMask(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
        */
    /** no mapping */
    rowreq_ctx->data.DirectoryEntryMask = DirectoryEntryMask;


    /*
        * insert into table container
        */
    CONTAINER_INSERT(container, rowreq_ctx);
}


/**
 * load initial data
 *
 * TODO:350:M: Implement DirectoryContentTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  DirectoryContentTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int DirectoryContentTable_container_load(netsnmp_container* container) {
    /*
     * temporary storage for index values
     */
    /*
     * DirectoryEntryIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
     */

    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_container_load",
         "called\n"));

    int count = walk_directory(get_global_settings()->path,
                               directory_info_loader, container);


    DEBUGMSGT(
        ("verbose:DirectoryContentTable:DirectoryContentTable_container_load",
         "inserted %d records\n", count));

    return MFD_SUCCESS;
} /* DirectoryContentTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void DirectoryContentTable_container_free(netsnmp_container* container) {
    DEBUGMSGTL(
        ("verbose:DirectoryContentTable:DirectoryContentTable_container_free",
         "called\n"));

    /*
     * TODO:380:M: Free DirectoryContentTable container data.
     */
} /* DirectoryContentTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int DirectoryContentTable_row_prep(
    DirectoryContentTable_rowreq_ctx* rowreq_ctx) {
    DEBUGMSGTL(("verbose:DirectoryContentTable:DirectoryContentTable_row_prep",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* DirectoryContentTable_row_prep */

/** @} */
