/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file DirectoryContentTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DIRECTORYCONTENTTABLE_DATA_GET_H
#define DIRECTORYCONTENTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table DirectoryContentTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MONITOR-MIB::DirectoryContentTable is subid 4 of netSnmpModuleIDs.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.8072.3.1.4, length: 10
*/
/*
 * indexes
 */

int DirectoryEntryPath_get(DirectoryContentTable_rowreq_ctx* rowreq_ctx,
                           char** DirectoryEntryPath_val_ptr_ptr,
                           size_t* DirectoryEntryPath_val_ptr_len_ptr);
int DirectoryEntryMask_get(DirectoryContentTable_rowreq_ctx* rowreq_ctx,
                           long* DirectoryEntryMask_val_ptr);


int DirectoryContentTable_indexes_set_tbl_idx(
    DirectoryContentTable_mib_index* tbl_idx, long DirectoryEntryIndex_val);
int DirectoryContentTable_indexes_set(
    DirectoryContentTable_rowreq_ctx* rowreq_ctx, long DirectoryEntryIndex_val);


#ifdef __cplusplus
}
#endif

#endif /* DIRECTORYCONTENTTABLE_DATA_GET_H */
/** @} */
