version: '3.1'

services:
  redis:
    image: redis:5.0.2
    restart: always
    ports:
      - '6379:6379'
  mongodb:
    image: mongodb:4.1.6
    restart: always
    ports:
      - '27017:27017'
      - '27018:27018'
      - '27019:27019'
