FROM ubuntu:16.04

#ENV http_proxy=http://<proxy>/
#ENV https_proxy=https://<proxy>/
#ENV ftp_proxy=ftp://<proxy>/
#ENV socks_proxy=socks://<proxy>/

#WORKDIR /tmp
#COPY Dockerfile /tmp

#RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y g++
