{
 "title": "ebpf-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "disk", "query": "sda, sdb, sdc, sdd, sde" }
  ]
 },
 "panels": [
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$disk - Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "repeat": "disk",
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{device=\"$disk\",operation=\"read\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$disk - Read Size",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "repeat": "disk",
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{device=\"$disk\",operation=\"read\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$disk - Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "repeat": "disk",
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{device=\"$disk\",operation=\"write\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$disk - Write Size",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "repeat": "disk",
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{device=\"$disk\",operation=\"write\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "File-Related Function Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ebpf_exporter_file_calls_total[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Run Queue Latency",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_run_queue_latency_seconds_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_run_queue_latency_seconds_sum[1m])/rate(ebpf_exporter_run_queue_latency_seconds_count[1m])"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Last Level Cache Accesses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ebpf_exporter_llc_references_total[1m]))",
     "legendFormat": "accesses"
    },
    {
     "expr": "sum(rate(ebpf_exporter_llc_misses_total[1m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(rate(ebpf_exporter_llc_misses_total[1m]))/sum(rate(ebpf_exporter_llc_references_total[1m]))",
     "legendFormat": "accesses"
    }
   ]
  },
  {
   "title": "Branch Instructions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ebpf_exporter_cpu_branch_instructions_total[1m]))",
     "legendFormat": "instructions"
    },
    {
     "expr": "sum(rate(ebpf_exporter_cpu_branch_misses_total[1m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Branch Prediction",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(rate(ebpf_exporter_cpu_branch_misses_total[1m]))/sum(rate(ebpf_exporter_cpu_branch_instructions_total[1m]))",
     "legendFormat": "hit"
    }
   ]
  },
  {
   "title": "Cycles + Instructions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ebpf_exporter_cpu_cycles_total[1m]))",
     "legendFormat": "cycles"
    },
    {
     "expr": "sum(rate(ebpf_exporter_cpu_instructions_total[1m]))",
     "legendFormat": "instructions"
    }
   ]
  },
  {
   "title": "Instructions / cycle",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ebpf_exporter_cpu_instructions_total[1m]))/sum(rate(ebpf_exporter_cpu_cycles_total[1m]))",
     "legendFormat": "instructions / cycle"
    }
   ]
  }
 ]
}