{
 "title": "netdata",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(netdata_cpu_cpu_percentage_average) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "expr": "netdata_system_ram_MiB_average", "legendFormat": "{{dimension}}" }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netdata_system_load_load_average{dimension=\"load1\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_system_load_load_average{dimension=\"load5\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_system_load_load_average{dimension=\"load15\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average",
     "legendFormat": "{{family}}-{{dimension}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "max(netdata_disk_io_KiB_persec_average{dimension=\"reads\"})",
     "legendFormat": "reads"
    },
    {
     "expr": "min(netdata_disk_io_KiB_persec_average{dimension=\"writes\"})",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_swap_MiB_average",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interrupts / core",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_cpu_softirqs_softirqs_persec_average) by (chart)",
       "legendFormat": "{{chart}}"
      }
     ]
    },
    {
     "title": "Interrupts / type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_system_softirqs_softirqs_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "netdata_cpufreq_cpufreq_MHz_average * 1000000",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Idle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_cpuidle_cpuidle_percentage_average",
       "legendFormat": "{{chart}}-{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_mem_pgfaults_faults_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Huge Page",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_mem_transparent_hugepages_MiB_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 TCP Active Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_tcpsock_active_connections_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "All Sockets (incl. unix)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_sockets_sockets_average",
       "legendFormat": "sockets"
      }
     ]
    },
    {
     "title": "IPv4 TCP Packets Transmit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_tcppackets_packets_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 UDP Packets Transmit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_udppackets_packets_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP Connections Open Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_tcpopens_connections_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP Sockets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 UDP Sockets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_udp_sockets_sockets_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 Socket Memory Consumption",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_tcp_mem_KiB_average",
       "legendFormat": "TCP"
      },
      {
       "expr": "-netdata_ipv4_sockstat_udp_mem_KiB_average",
       "legendFormat": "UDP"
      }
     ]
    },
    {
     "title": "TCP Out of Order Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "netdata_ip_tcpofo_packets_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "TCP Reorder Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "netdata_ip_tcpreorders_packets_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "TCP Inerror Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "netdata_ip_inerrors_packets_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "TCP Abort Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "netdata_ip_tcpconnaborts_connections_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 Packet Transmit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv6_packets_packets_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 Sockets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv6_sockstat6_tcp_sockets_sockets_average",
       "legendFormat": "TCP"
      },
      {
       "expr": "-netdata_ipv6_sockstat6_udp_sockets_sockets_average",
       "legendFormat": "UDP"
      }
     ]
    }
   ]
  },
  {
   "title": "DISK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_io_KiB_persec_average",
       "legendFormat": "{{family}}-{{dimension}}"
      }
     ]
    },
    {
     "title": "OPS Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_ops_operations_persec_average",
       "legendFormat": "{{family}}-{{dimension}}"
      }
     ]
    },
    {
     "title": "Merged OPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_mops_merged_operations_persec_average",
       "legendFormat": "{{family}}-{{dimension}}"
      }
     ]
    },
    {
     "title": "IO Request Wait Time",
     "type": "graph",
     "description": "Time spent waiting for device to serve requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_await_milliseconds_operation_average",
       "legendFormat": "{{family}}-{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PROCESSES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory / app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      { "expr": "netdata_apps_mem_MiB_average", "legendFormat": "{{dimension}}" }
     ]
    },
    {
     "title": "Virtual Memory / app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      { "expr": "netdata_apps_vmem_MiB_average", "legendFormat": "{{dimension}}" }
     ]
    },
    {
     "title": "CPU Average / app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_cpu_percentage_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Uptime / app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_uptime_seconds_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU User Average / app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_cpu_user_percentage_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Minor Page Faults",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_minor_faults_page_faults_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU System Average / app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_cpu_system_percentage_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Process Creation Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_system_forks_processes_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_files_open_files_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Open Sockets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_sockets_open_sockets_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_threads_threads_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_processes_processes_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Logical Reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_lreads_KiB_persec_average",
       "legendFormat": "{{dimension}}"
      },
      {
       "expr": "netdata_apps_lwrites_KiB_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Logical Writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_lwrites_KiB_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Physical Reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_preads_KiB_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Physical Writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_pwrites_KiB_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SERVICES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU / service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_services_cpu_percentage_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Memory / service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_services_mem_usage_MiB_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SCHEDULER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_system_ctxt_context_switches_persec_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OTHERS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Entropy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_system_entropy_entropy_average",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  }
 ]
}