{
 "title": "node-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Level Cache Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_perf_cache_ll_read_hits_total[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(node_perf_cache_ll_read_misses_total[1m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Last Level Cache Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_perf_cache_ll_write_hits_total[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(node_perf_cache_ll_write_misses_total[1m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "L1D Cache Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_perf_cache_l1d_read_hits_total[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(node_perf_cache_l1d_read_misses_total[1m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-avg_over_time(node_perf_cache_misses_total[1m])/avg_over_time(node_perf_cache_refs_total[1m])",
     "legendFormat": "accesses"
    }
   ]
  },
  {
   "title": "Branch Instructions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_perf_branch_instructions_total[1m])",
     "legendFormat": "instructions"
    },
    {
     "expr": "rate(node_perf_branch_misses_total[1m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Branch Prediction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-rate(node_perf_branch_misses_total[1m])/rate(node_perf_branch_instructions_total[1m])",
     "legendFormat": "hit"
    }
   ]
  },
  {
   "title": "CPU Time / CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (cpu)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Time / mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{chip}}-{{sensor}}" }
   ]
  },
  {
   "title": "Interrupts / CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_interrupts_total[1m])) by (cpu)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Interrupts / type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_interrupts_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" },
      { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "available" }
     ]
    },
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(node_vmstat_pgfault[1m])", "legendFormat": "faults" }
     ]
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Send Rate (packets)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_packets_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Network Send Rate (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Network Receive Rate (packets)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Network Receive Rate (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "TCP Out Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_OutSegs[1m])",
       "legendFormat": "packets"
      }
     ]
    },
    {
     "title": "UDP Out Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_OutDatagrams[1m])",
       "legendFormat": "packets"
      }
     ]
    },
    {
     "title": "TCP In Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InSegs[1m])",
       "legendFormat": "packets"
      }
     ]
    },
    {
     "title": "UDP In Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InDatagrams[1m])",
       "legendFormat": "packets"
      }
     ]
    },
    {
     "title": "TCP Retransmit Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs[1m])",
       "legendFormat": "packets"
      }
     ]
    },
    {
     "title": "TCP In Error Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InErrs[1m])",
       "legendFormat": "packets"
      }
     ]
    },
    {
     "title": "TCP Active Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens[1m])",
       "legendFormat": "connections"
      }
     ]
    }
   ]
  },
  {
   "title": "DISK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read Data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Written Data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Read Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Write Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_write_time_seconds_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk IO Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk IO Ops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      { "expr": "node_disk_io_now", "legendFormat": "{{device}}" }
     ]
    },
    {
     "title": "File FD Allocated",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_filefd_allocated", "legendFormat": "allocated" }
     ]
    }
   ]
  },
  {
   "title": "PROCESSES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_processes_pids", "legendFormat": "processes" },
      { "expr": "node_processes_threads", "legendFormat": "threads" }
     ]
    },
    {
     "title": "Process State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_processes_state", "legendFormat": "{{state}}" }
     ]
    },
    {
     "title": "Forking Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(node_forks_total[1m])", "legendFormat": "forks" }
     ]
    }
   ]
  },
  {
   "title": "OTHER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches_total[1m])"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      { "expr": "node_entropy_available_bits", "legendFormat": "entropy" }
     ]
    }
   ]
  }
 ]
}