version: '3.1'

services:
  db:
    build: ./postgresql
    restart: always
    env_file:
      - vars.env
  app:
    build: ./app
    restart: "no"
    env_file:
      - vars.env
  adminer:
    image: adminer
    restart: always
    ports:
      - "58080:8080"
