FROM ubuntu:16.04

RUN DEBIAN_FRONTEND=noninteractive; apt-get update
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y apt-utils
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y g++
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y clang libclang-dev
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y cmake
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y zlib1g-dev
