#!/bin/bash

EMAIL=$(git config --local user.email)
if [ -z "$EMAIL" ]; then
    echo "ERROR: Missing local user.email."
    exit 1
fi

NAME=$(git config --local user.name)
if [ -z "$EMAIL" ]; then
    echo "ERROR: Missing local user.name."
    exit 1
fi

exit 0

