FROM ubuntu:16.04

#ENV http_proxy=http://<proxy>:<port>/
#ENV https_proxy=https://<proxy>:<port>/
#ENV ftp_proxy=ftp://<proxy>:<port>/
#ENV socks_proxy=socks://<proxy>:<port>/

#ARG DEBIAN_FRONTEND=noninteractive

#RUN apt-get update
#RUN apt-get install -y apt-utils
#RUN apt-get install -y locales
#RUN dpkg-reconfigure locales && locale-gen en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
#RUN apt-get upgrade -y

#RUN apt-get install -y g++ gdb

#RUN apt-get clean -y
#RUN rm -rf /var/lib/apt/lists/*

#WORKDIR /tmp
#COPY Dockerfile /tmp
