CREATE TABLE PRODUCTS(
    ID INT PRIMARY KEY NOT NULL,
    NAME text NOT NULL,
    PRICE decimal NOT NULL
);

INSERT INTO PRODUCTS(ID, NAME, PRICE) VALUES (1, 'A', 1.1);
INSERT INTO PRODUCTS(ID, NAME, PRICE) VALUES (2, 'B', 2.2);
INSERT INTO PRODUCTS(ID, NAME, PRICE) VALUES (3, 'C', 3.3);
